### ISSUE TITLE
Strange behavior of `0.5.4` for `ComposerFinder::inNamespace`

### ISSUE THREAD

**Issue by andrew-demb** [alekitto/class-finder#24]
I'm in the process of making `graphqlite-bundle` compatible with `graphqlite` v7 (dev) and `symfony` v7 
(continuation from PR https://github.com/thecodingmachine/graphqlite-bundle/pull/203; here's a permalink to the used `graphqlite` dependency version https://github.com/thecodingmachine/graphqlite/tree/0f1a112fe46a131fb6564b2f1001b5dc6d35b075)

While investigating issues with test suite I found, that `ComposerFinder::inNamespace` does autoload of unrelated classes (not related to the requested namespace).

![image](https://github.com/user-attachments/assets/39968312-4737-4818-a6c4-3bf27223b1cd)

![image](https://github.com/user-attachments/assets/7b0a168d-ecd5-4c15-8407-1dfac12f8e81)

Please suggest a path to investigate the reason for such behavior and how to fix it (should it be a fix in `class-finder` or in `graphqlite`?)

----

The reason, why I am investigating it - is because of that behavior - in `graphqlite-bundle` tests there's an error about redeclaring an existent class.

![image](https://github.com/user-attachments/assets/6d42bc97-fcda-496f-a349-4e7c53f6ed68)

**Comment by andrew-demb** [comment]
I found the reason for such behavior of `class-finder` - in `graphqlite-bundle` there was an autoload section described like this:
```
"autoload" : {
    "psr-4" : {
      "TheCodingMachine\\GraphQLite\\Bundle\\" : ""
    }
  },
```

I changed the bundle's directory structure to move the source code to the `src` and tests source code to the `tests` and the error about redeclaring Twig classes is gone.

----

For now, I have another error: `PHP Fatal error:  Cannot declare class BadClass, because the name is already in use in /home/hidden/php/github/graphqlite-bundle/tests/Fixtures/Entities/BadClass.php on line 5`

Context: https://github.com/andrew-demb/graphqlite-bundle/pull/1
![image](https://github.com/user-attachments/assets/a6bdbfa8-6f62-4ef4-96f0-75605fbd1c0d)
![image](https://github.com/user-attachments/assets/a42dab2f-9fbc-4ae0-b836-781be99c1dd9)

Commit that introduced test with ignoring bad class https://github.com/thecodingmachine/graphqlite-bundle/commit/d221cb19c8dfeaaeea9464683b8aa7c3957941d7#diff-c10c2bd297e9e7ba6de365b2ed643b3cf48e114110664533a61de233e61bc4d2R425

Code that initiates a search for classes in test namespace: https://github.com/andrew-demb/graphqlite-bundle/blob/ff06ee1548b2e95918f937e11073bc0f7eed67fd/src/DependencyInjection/GraphQLiteCompilerPass.php#L484-L491

Please hint whether I can have the same behavior about ignoring bad classes with `class-finder`

**Comment by alekitto** [comment]
Hi @andrew-demb,
For the first part: yes, it expected for the class finder to load the classes inside the folders where *there's a chance* to find the requested namespace prefixes according to the `composer.json` file.

The second part is trickier, but to make it short, it is caused by https://github.com/composer/composer/issues/6987 and it cannot be fixed: the presence of a global class or a global function (or a misspelled namespace) inside a PSR-0/4 structure will break the autoloader and the finder if not used with a generated authoritative classmap.
The only way to avoid that is to explicitly exclude those files via `pathFilter`; in your case you can probably let the user to configure an array of paths to be excluded from the search.

**Comment by andrew-demb** [comment]
Thank you, @alekitto.
